name: Test

on:
  pull_request

jobs:
  test:
    runs-on: macos-12
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - uses: irgaly/setup-mint@v1
        with:
          cache-prefix: "mint"

      - name: create mocks
        run: make mock

      - name: execute tests
        run: make test
